# Generated by Django 3.1.3 on 2020-11-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromuser', models.CharField(max_length=30)),
                ('fromsite', models.CharField(max_length=30)),
                ('nodename', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='site_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=30)),
                ('nodename', models.CharField(max_length=30)),
                ('cfgjson', models.JSONField()),
            ],
        ),
    ]
