# Generated by Django 3.1.3 on 2020-11-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='context_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctxname', models.CharField(max_length=30)),
                ('vpnrd', models.CharField(max_length=30)),
                ('ints', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='book_info',
        ),
        migrations.DeleteModel(
            name='site_info',
        ),
    ]
